/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ActivityLogs: () => import('#controllers/activity_logs_controller'),
  Applications: () => import('#controllers/applications_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Chatbot: () => import('#controllers/chatbot_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Interviews: () => import('#controllers/interviews_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Offers: () => import('#controllers/offers_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Users: () => import('#controllers/users_controller'),
}
