// TypeScript validation stub for @prisma/client.
// The real client is generated by `prisma generate` at build time (needs network
// for engine binaries). This stub lets `tsc` type-check the codebase offline.
// It is intentionally loose but models the shapes used across the app.
declare module "@prisma/client" {
  export type UserRole = "admin" | "rh" | "candidat";
  export type OfferType = "stage" | "emploi";
  export type OfferStatus = "brouillon" | "publiee" | "fermee";
  export type ApplicationStatus =
    | "envoyee"
    | "en_cours_analyse"
    | "entretien_programme"
    | "acceptee"
    | "rejetee";
  export type InterviewMode = "presentiel" | "distanciel";
  export type InterviewStatus = "planifie" | "termine" | "annule";
  export type ChatRole = "user" | "assistant";

  export type User = {
    id: number;
    fullName: string | null;
    email: string;
    password: string;
    role: UserRole;
    phone: string | null;
    isActive: boolean;
    mustChangePassword: boolean;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type CandidateProfile = {
    id: number;
    userId: number;
    bio: string | null;
    skills: string | null;
    cvUrl: string | null;
    aiExtractedData: unknown;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type Offer = {
    id: number;
    title: string;
    type: OfferType;
    description: string;
    requirements: string | null;
    deadline: Date | null;
    location: string | null;
    status: OfferStatus;
    aiAnalysisCriteria: string | null;
    createdBy: number;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type Application = {
    id: number;
    offerId: number;
    userId: number;
    cvUrl: string | null;
    coverLetterUrl: string | null;
    coverLetterText: string | null;
    status: ApplicationStatus;
    aiMatchScore: number | null;
    aiSummary: string | null;
    aiAnalyzedAt: Date | null;
    aiAnalysisData: unknown;
    appliedAt: Date;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type Interview = {
    id: number;
    applicationId: number;
    scheduledAt: Date;
    meetingLink: string | null;
    mode: InterviewMode;
    status: InterviewStatus;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type Notification = {
    id: number;
    userId: number;
    type: string;
    content: string;
    readAt: Date | null;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type ChatbotMessage = {
    id: number;
    userId: number | null;
    role: ChatRole;
    content: string;
    createdAt: Date;
    updatedAt: Date | null;
  };

  export type ActivityLog = {
    id: number;
    userId: number;
    action: string;
    category: string;
    summary: string;
    resourceType: string | null;
    resourceId: number | null;
    metadata: unknown;
    ipAddress: string | null;
    userAgent: string | null;
    createdAt: Date;
  };

  export namespace Prisma {
    type StringFilter = { contains?: string; mode?: "insensitive" | "default"; equals?: string };
    export type OfferWhereInput = {
      status?: OfferStatus;
      type?: OfferType;
      location?: StringFilter | string | null;
      title?: StringFilter | string;
      description?: StringFilter | string;
      requirements?: StringFilter | string | null;
      OR?: OfferWhereInput[];
      AND?: OfferWhereInput[];
    };
    export type ActivityLogWhereInput = {
      userId?: number;
      category?: string;
      action?: string;
      summary?: StringFilter | string;
      user?: { role?: { in?: UserRole[] } };
    };
    export type ApplicationWhereInput = Record<string, unknown>;
  }

  type Delegate = {
    findUnique: (args: unknown) => Promise<any>;
    findFirst: (args?: unknown) => Promise<any>;
    findMany: (args?: unknown) => Promise<any[]>;
    create: (args: unknown) => Promise<any>;
    update: (args: unknown) => Promise<any>;
    upsert: (args: unknown) => Promise<any>;
    delete: (args: unknown) => Promise<any>;
    deleteMany: (args?: unknown) => Promise<{ count: number }>;
    updateMany: (args: unknown) => Promise<{ count: number }>;
    count: (args?: unknown) => Promise<number>;
    groupBy: (args: unknown) => Promise<any[]>;
  };

  export class PrismaClient {
    constructor(options?: unknown);
    user: Delegate;
    candidateProfile: Delegate;
    offer: Delegate;
    application: Delegate;
    applicationStatusHistory: Delegate;
    interview: Delegate;
    notification: Delegate;
    chatbotMessage: Delegate;
    activityLog: Delegate;
    $disconnect: () => Promise<void>;
    $connect: () => Promise<void>;
  }
}
