/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivityLogSchema extends BaseModel {
  static $columns = ['action', 'category', 'createdAt', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'summary', 'userAgent', 'userId'] as const
  $columns = ActivityLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare resourceId: number | null
  @column()
  declare resourceType: string | null
  @column()
  declare summary: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number
}

export class ApplicationStatusHistorySchema extends BaseModel {
  static $columns = ['applicationId', 'changedAt', 'changedBy', 'createdAt', 'id', 'status', 'updatedAt'] as const
  $columns = ApplicationStatusHistorySchema.$columns
  @column()
  declare applicationId: number
  @column.dateTime()
  declare changedAt: DateTime
  @column()
  declare changedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApplicationSchema extends BaseModel {
  static $columns = ['aiAnalysisData', 'aiAnalyzedAt', 'aiMatchScore', 'aiSummary', 'appliedAt', 'coverLetterText', 'coverLetterUrl', 'createdAt', 'cvUrl', 'id', 'offerId', 'status', 'updatedAt', 'userId'] as const
  $columns = ApplicationSchema.$columns
  @column()
  declare aiAnalysisData: any | null
  @column.dateTime()
  declare aiAnalyzedAt: DateTime | null
  @column()
  declare aiMatchScore: number | null
  @column()
  declare aiSummary: string | null
  @column.dateTime()
  declare appliedAt: DateTime
  @column()
  declare coverLetterText: string | null
  @column()
  declare coverLetterUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cvUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare offerId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateProfileSchema extends BaseModel {
  static $columns = ['aiExtractedData', 'bio', 'createdAt', 'cvUrl', 'id', 'skills', 'updatedAt', 'userId'] as const
  $columns = CandidateProfileSchema.$columns
  @column()
  declare aiExtractedData: any | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cvUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare skills: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ChatbotMessageSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = ChatbotMessageSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class InterviewSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'id', 'meetingLink', 'mode', 'notes', 'scheduledAt', 'status', 'updatedAt'] as const
  $columns = InterviewSchema.$columns
  @column()
  declare applicationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meetingLink: string | null
  @column()
  declare mode: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'readAt', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OfferSchema extends BaseModel {
  static $columns = ['aiAnalysisCriteria', 'createdAt', 'createdBy', 'deadline', 'description', 'id', 'location', 'requirements', 'status', 'title', 'type', 'updatedAt'] as const
  $columns = OfferSchema.$columns
  @column()
  declare aiAnalysisCriteria: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deadline: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column()
  declare requirements: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'mustChangePassword', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare mustChangePassword: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
